### PR TITLE
Prettyblocks toolbar for iframe navigation

### PR DESCRIPTION
**Pull request by axometeam**
### Prettyblocks toolbar for navigation inside iframe

-  **ToolbarCheckerHandler** to check if iframe can be displayed
-  **ToolbarCheckerInterface** to add display conditions
-  **ToolbarDataProvider** to request contents links (Product/Category/CMS)   

### Hooks structure  refacto

- Move all hooks in **src/Module/Hook/** folder
- Same structure as ClassicBlocks

### CODE REVIEW

**Comment by PrestaSafe** [comment]
Hi, thanks for your PR, but i'm actually facing some issues: 

Default Shop not selected
Capture d’écran 2023-05-05 à 16 36 01

Zone not detected:

**Comment by PrestaSafe** [comment]
Hi !
Thanks for you PR. 

I've actually some issues: 
Capture d’écran 2023-05-05 à 16 39 17

I've reset prettyblocks
`composer update` 
then 
`npm update && npm run build` 
The popup is displayed (imgs missing maybe cause of .gitignore)
But zones are not detected and the default shop not working. 

I've missed something ? 

Thanks

**Comment by jf-viguier** [comment]
Thanks @axometeam for your work.
Hooks structure refacto should be in another PR, can you do that ? (just a suggestion)

**Comment by PrestaSafe** [comment]
hey @aaraujoaxome we add the ?prettyblocks=1 in every url that prettyblocks will serve. 
So, if you want to, you can now fix easily your PR. 
Tell me if you steel want to make this PR or i close it. 

Thanks !

**Comment by aaraujoaxome** [comment]
Hi !
We will try to correct the PR next week with Mickael.
If it's not done by then, you can delete ;)
[image: Axome] <https://www.axome.com>

*Antoine Araujo*

Agence e-commerce, design et marketing
0477813813
[image: linkedin]
<https://signitic.app/l/RFdGREd5U3V0ancyam53STB4YW41dz09-SGFZSjBLKzN4YXBzU3JlTGJ6WU41dz09>
[image: web]
<https://signitic.app/l/RFdGREd5U3V0ancyam53STB4YW41dz09-VzNGNG5oU1pWYjZRMTVQMUxBZ2xJZz09>
[image: instagram]
<https://signitic.app/l/RFdGREd5U3V0ancyam53STB4YW41dz09-MVc4eTk5YXpOcDFSNDR3dDdleFhiQT09>


Le jeu. 26 oct. 2023 à 17:37, Guillaume Batier ***@***.***> a
écrit :

**Pull request closed without merging**
