### PR TITLE
Employee connected

### PR DESCRIPTION
**Pull request by axometeam**
Alert message when more than one employee is in edit mode in the backoffice.
 To avoid modifications by two employees at the same time which corrupts the blocks in the database

### CODE REVIEW

**Comment by axometeam** [comment]
image

**Comment by PrestaSafe** [comment]
Hi and many thanks for the PR ! 
It's a very great update for PrettyBlocks. 
I have noticed some few errors, but, in my case, the `connected_employee` is not feed and i don't really know why. 
The Front Controller return me and
```
{success: false} 
``` 
all the time. 
i'll make for test to find why it's not working fine.

**Comment by PrestaSafe** [comment]
ok found it: 
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lastpresta.ps_prettyblocks_editing_users' doesn't exist`
@axometeam can you give me the schema of this table please ?

**Comment by axometeam** [comment]
Hello :)
Normally the table is supposed to be installed when the module is installed. There is a new "makeConnectedEmployee" method in the main module file. There is the table structure in it :)
Small error on our side on the table name, this is corrected in the last commit

**Review by PrestaSafe — APPROVED** [review]

**Comment by PrestaSafe** [comment]
moving into #269

**Pull request closed without merging**
